package sso

import (
	"fmt"
	"net/http"
	"os"

	"github.com/common-fate/cli/pkg/awscfg"
	"github.com/common-fate/cli/pkg/client"
	"github.com/common-fate/cli/pkg/config"
	"github.com/urfave/cli/v2"
	"gopkg.in/ini.v1"
)

var populate = cli.Command{
	Name:  "populate",
	Usage: "Populate AWS config file with available Access Rules, writing to ~/.aws/config",
	Flags: []cli.Flag{
		&cli.StringFlag{Name: "sso-start-url", Required: true, Usage: "the AWS SSO start URL (e.g. https://d-123456abc.awsapps.com/start)"},
		&cli.StringFlag{Name: "commonfate-url", Usage: "the Common Fate dashboard URL (e.g. https://commonfate.example.com)"},
		&cli.StringFlag{Name: "sso-region", Required: true, Usage: "the AWS SSO region"},
		&cli.StringFlag{Name: "prefix", Usage: "Specify a prefix for all generated profile names"},
		&cli.BoolFlag{Name: "no-credential-process", Usage: "Generate profiles without the Granted credential-process integration"},
		&cli.StringFlag{Name: "profile-template", Usage: "Specify profile name template", Value: "{{ .AccountName }}/{{ .RoleName }}"},
	},
	Action: func(c *cli.Context) error {
		ctx := c.Context

		cfg, err := config.Load()
		if err != nil {
			return err
		}

		cf, err := client.FromConfig(ctx, cfg)
		if err != nil {
			return err
		}
		rules, err := cf.UserListAccessRulesWithResponse(ctx)
		if err != nil {
			return err
		}
		if rules.StatusCode() != http.StatusOK {
			return fmt.Errorf("%s", string(rules.Body))
		}

		var profiles []awscfg.SSOProfile

		for _, r := range rules.JSON200.AccessRules {
			ruleDetail, err := cf.UserGetAccessRuleWithResponse(ctx, r.ID)
			if err != nil {
				return err
			}

			// only rules for the aws-sso Access Provider are relevant here
			if ruleDetail.JSON200.Target.Provider.Type != "aws-sso" {
				continue
			}

			accountId := ruleDetail.JSON200.Target.Arguments.AdditionalProperties["accountId"]
			permissionSetArn := ruleDetail.JSON200.Target.Arguments.AdditionalProperties["permissionSetArn"]

			// add all options to our profile map
			for _, acc := range accountId.Options {
				for _, ps := range permissionSetArn.Options {
					p := awscfg.SSOProfile{
						AccountId:     acc.Value,
						AccountName:   acc.Label,
						RoleName:      ps.Label,
						StartUrl:      c.String("sso-start-url"),
						SSORegion:     c.String("sso-region"),
						CommonFateURL: c.String("commonfate-url"),
					}
					profiles = append(profiles, p)
				}
			}
		}

		configFilename := awscfg.DefaultSharedConfigFilename()

		config, err := ini.LoadSources(ini.LoadOptions{
			AllowNonUniqueSections:  false,
			SkipUnrecognizableLines: false,
		}, configFilename)
		if err != nil {
			if !os.IsNotExist(err) {
				return err
			}
			config = ini.Empty()
		}

		// remove any existing profiles generated by Common Fate
		for _, c := range config.Sections() {
			k, err := c.GetKey("generated_by_common_fate")
			if err != nil {
				continue
			}
			if k.String() == "true" {
				config.DeleteSection(c.Name())
			}
		}

		err = awscfg.Merge(awscfg.MergeOpts{
			Config:              config,
			Prefix:              c.String("prefix"),
			SectionNameTemplate: c.String("profile-template"),
			Profiles:            profiles,
			NoCredentialProcess: c.Bool("no-credential-process"),
		})
		if err != nil {
			return err
		}

		err = config.SaveTo(configFilename)
		if err != nil {
			return err
		}
		return nil
	},
}
